apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgraph
  labels:
    app: dgraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dgraph
  template:
    metadata:
      labels:
        app: dgraph
    spec:
      containers:
      - name: zero
        image: dgraph/dgraph:latest
        args: [
          "dgraph", "zero",
          "--my=zero:5080"
        ]
        ports:
        - containerPort: 5080
          name: grpc-zero
          protocol: TCP
        - containerPort: 6080
          name: http-zero
          protocol: TCP
        volumeMounts:
        - name: datadir
          mountPath: /dgraph
      - name: alpha
        image: dgraph/dgraph:latest
        args: [
          "dgraph", "alpha",
          "--my=alpha:7080",
          "--zero=zero:5080"
        ]
        ports:
        - containerPort: 8080
          name: http-alpha
          protocol: TCP
        - containerPort: 9080
          name: grpc-alpha
          protocol: TCP
        volumeMounts:
        - name: datadir
          mountPath: /dgraph
      - name: ratel
        image: dgraph/ratel:latest
        ports:
        - containerPort: 8000
          name: http-ratel
          protocol: TCP
      volumes:
      - name: datadir
        emptyDir: {}
